stages:
  - build

build-a-windows:
  stage: build
  tags: windows
  script:
    - build_if_changed.bat a dir /A

build-a-unix:
  stage: build
  tags: unix
  script:
    - ./build_if_changed.sh a ls

build-b:
  stage: build
  script:
    - ./build_if_changed.sh b ls -hal
