# needs `curl`, `jq` 1.5 and `${PRIVATE_TOKEN}, cf.:
# - https://docs.gitlab.com/ee/api/#personal-access-tokens
# - https://docs.gitlab.com/ce/ci/variables/README.html#secret-variables
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_SERVER_URL: https://gitlab.com
before_script:
    - .monorepo.gitlab/last_green_commit.sh

stages:
  - build

build-a-linux:
  stage: build
  tags: 
    - linux
  # example for one liner (preferred) on linux
  script:
    - .monorepo.gitlab/build_if_changed.sh a cat a/README.md

build-a-windows:
  stage: build
  tags: 
    - windows
  # example for one liner (preferred) on windows
  script:
    - .monorepo.gitlab\build_if_changed.bat a type a\README.md
  # disable this windows build for now
  when: manual

build-b:
  stage: build
  tags: 
    - linux
  # example for multiple lines (discouraged) on linux
  script:
    - if [[ $(.monorepo.gitlab/changes.sh b) -ne 0 ]]; then echo "Skipping build for '${folder}'." && exit 0; fi
    - cd b
    - ls -hal
